### ISSUE TITLE
 [gatsby-plugin-graphql-codegen] gatsby 3.0.0 compatibility

### ISSUE THREAD

**Issue by GayaneKasparova** [d4rekanguok/gatsby-typescript#116]
**Describe the bug**
gatsby-plugin-graphql-codegen plugin doesn't work after gatsby update to 3.0.0

**To Reproduce**
  Installed packages
        "gatsby": "^3.0.0",
        "gatsby-plugin-graphql-codegen": "^2.7.1",
        "gatsby-plugin-typescript": "^3.0.0",
        "graphql": "^15.5.0",
        "react": "^17.0.1",
        "react-dom": "^17.0.1",
        "typescript": "^4.2.2"

**Environment (please complete the relevant info):**
- OS (Mac, Linux, Window, etc.) --> Windows10 64bit
- Gatsby version --> 3.0.0
- Typescript version --> 4.2.2

**Comment by dvakatsiienko** [comment]
Voting up for this one! Also can't spin up setup with gatsby-typescript using Gatsby 3+

**Comment by arthurkhlghatyan** [comment]
Hey there,

Same issue on my end. 

Also got hot reloading blocked.

Thanks.

**Comment by jephjohnson** [comment]
Bump, blocked also. Any updates on this? Appreciate you guys

**Comment by stschwark** [comment]
I've not actually had problems yet with Gatsby 3.3.1 apart from a warning message saying `Plugin gatsby-plugin-graphql-codegen is not compatible with your gatsby version 3.3.1 - It requires gatsby@^2.12.1` which is down to the declared peer dependency.

What were the other issues?

**Comment by dustinlacewell** [comment]
It's pretty slow and seems to rebuild the typings multiple times on startup and every change.

**Comment by alvis** [comment]
@stschwark if you use npm v7+ then you can't even be able to install it due to peer dependency conflict. Unless you use the `--force` flag, you've no luck other than using other similar plugins like `gatsby-plugin-typegen`.

**Comment by d4rekanguok** [comment]
Hi everyone, my apologies for leaving this repo in the dust — happy to merge any working PRs. If you'd like to take ownership / become maintainers of this repo, please get in touch.

**Comment by alvis** [comment]
@d4rekanguok Thanks for your kind invite. I'm interested to be a maintainer of `gatsby-plugin-graphql-codegen`. Unlikely I can make any substantial contribution due to my limited time as well, but at least I can help to make the package compatible with other packages.
Will make a PR to update the dependency soon.

**Comment by alvis** [comment]
@d4rekanguok PRs have been made for v2 #129 and v3 #130.
You can trigger the test and review.

**Comment by d4rekanguok** [comment]
Thanks so much @alvis — you're a legend for stepping up & taking this issue. I have published new versions for v2 (2.7.3) and v3 (3.0.0) as suggested.

**Comment by alvis** [comment]
You're welcome @d4rekanguok. I'm just solving my pain as a ts enthusiast.
I'm tried both v2 & v3 on my personal projects and they're all so far so good. 😀
