### ISSUE TITLE
[gatsby-plugin-graphql-codegen] ExperimentalWarning: stream/web is an experimental feature

### ISSUE THREAD

**Issue by caleb531** [d4rekanguok/gatsby-typescript#142]
**Describe the bug**

When I recently installed `gatsby-plugin-graphql-codegen` into my new Gatsby project, I receive the following warning when running `gatsby build`:

```
 ERROR 

(node:27912) ExperimentalWarning: stream/web is an experimental feature. This
feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

The plugin still seems to work fine, and my local development process isn't halted. But I am concerned about the stability of this plugin from a warning like this.

**To Reproduce**

1. Clone my reproduction project: https://github.com/caleb531/gatsby-graphql-codegen-warning
2. Run `npm install`
3. Run `gatsby develop`
4. You will see the above error/warning in the output:

**Environment (please complete the relevant info):**
- macOS Monterey (v12.1)
- Gatsby v4.4.0
- TypeScript v4.5.4
- Node v16.5.0
- gatsby-plugin-graphql-codegen v3.1.0

**Additional context**
Add any other context about the problem here, `gatsby-config`, `tsconfig.json`, etc.

Per my test repository, I have successfully reproduced the issue where `gatsby-plugin-graphql-codegen
` is the _only_ plugin in `gatsby-config.js`:
https://github.com/caleb531/gatsby-graphql-codegen-warning

**Comment by darylwright** [comment]
Running `cross-env GATSBY_GRAPHQL_IDE=playground NODE_OPTIONS="--trace-warnings" gatsby develop --verbose` produces the following output:

```
 ERROR 

(node:3480) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at node:stream/web:7:1
    at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
    at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
    at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
    at Function.Module._load (node:internal/modules/cjs/loader:804:15)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (<PATH REDACTED>\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (<PATH REDACTED>\node_modules\cross-undici-fetch\dist\node-ponyfill.js:31:24)
    at Module._compile (<PATH REDACTED>\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (<PATH REDACTED>\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (<PATH REDACTED>\node_modules\@graphql-tools\url-loader\index.js:37:26)

```

This appears to be a problem with the `@graphql-tools/url-loader` library based on the trace information. The line in question within this library is an import:

```
const crossUndiciFetch = require('cross-undici-fetch');
```

`cross-undici-fetch` requires `stream/web` in [`https://github.com/ardatan/w3-server/blob/master/packages/cross-undici-fetch/dist/node-ponyfill.js`](https://github.com/ardatan/w3-server/blob/master/packages/cross-undici-fetch/dist/node-ponyfill.js) on line 31. This library was introduced in [this commit](https://github.com/ardatan/graphql-tools/commit/41d9a99629b9a879397abb4726195045b640ffec#diff-21b2136fb5aa374c937db6158dd84f4338369d97da0a59ba802c502dd00cc913) of `@graphql-tools/url-loader`.

`gatsby-plugin-graphql-codegen` currently has `v7.0.0` (i.e. `^7.0.0` with the current version at `v7.7.1`) of the `@graphql-tools/url-loader` as a dependency and is used in `packages/gatsby-plugin-graphql-codegen/src/gatsby-node.ts`. Latest commit for this is `8219851` on Oct 28, 2021. Before that on commit `e68b6d5`, `@graphql-tools/url-loader` was at `v6.10.1`.

It seems the folks in the `@graphql-tools` team thought it was a good idea to use an experimental feature for a production release. Until these upstream issues are resolved, the current solution should be for devs to rollback their `gatsby-plugin-graphql-codegen` dependencies to `v3.0.0` or the latest `v2` if possible. I can confirm that rolling back to `v3.0.0` (exact version only) resolves this error, albeit with the following warning:

```
warn Plugin gatsby-plugin-graphql-codegen is not compatible with your gatsby version 4.6.0 - It requires gatsby@^3.0.0
```

As far as this project goes, the `@graphql-tools/url-loader` version should be rolled back to the last one that does not use `cross-undici-fetch`, namely [`v7.4.2`](https://github.com/ardatan/graphql-tools/blob/33afe6bfadb20ffd6cce3e4af55400a0646ce2dd/packages/loaders/url/package.json).

**Comment by igneosaur** [comment]
I just moved to [`gatsby-plugin-typegen`](https://www.npmjs.com/package/gatsby-plugin-typegen).

**Comment by darylwright** [comment]
I've confirmed that I no longer experience this issue with `v3.1.1`. This issue can be closed.
