### ISSUE TITLE
(gatsby-plugin-ts) Error with latest Gatsby

### ISSUE THREAD

**Issue by d4rekanguok** [d4rekanguok/gatsby-typescript#24]
>  ERROR #98123  WEBPACK
>
> Generating SSR bundle failed
>
> Cannot find module '@babel/preset-typescript' from '/Users/derek/Documents/Documents/Projects/opensource/byderek.com'
>
> File: .cache/api-ssr-docs.js

Likely Gatsby internal assuming presence of `gatsby-plugin-typescript`? Need to look into this more

**Comment by jseto** [comment]
Should close. Now it's fixed.

**Comment by d4rekanguok** [comment]
Thank you @jseto, that's great to hear! I'll give it another try. Did you also run into the same problem?

**Comment by jseto** [comment]
Yes. I thought you fixed in your last release as it is working now.

**Comment by d4rekanguok** [comment]
Hah, I didn't touched anything regarding to this issue at all — it seems fixed. Perhaps a Gatsby patch release fixed it? Will close for now, thank you again for reporting in!
