### ISSUE TITLE
Inline Fragments aren't exported

### ISSUE THREAD

**Issue by johnrom** [d4rekanguok/gatsby-typescript#54]
I'm experimenting with Gatsby + TypeScript, while having `gatsby-plugin-graphql-codegen` generate all types which come from GraphQL. Using this with inline fragments + interfaces doesn't export the types for the fragments to be consumed by components' props. This means I'd have to duplicate types for all widgets.

Please export the fragments as well.

Example:

```ts
export const createSchemaCustomization = ({
  { createTypes },
}: CreateSchemaCustomizationArgs) => {
  const typeDefs = `
    type Image {
      src: File! @fileByRelativePath
      alt: String
      caption: String
    }
    interface Widget {
      widgetId: String!
      widgetType: String!
    }
    type ImageSliderWidget implements Widget {
      widgetId: String!
      widgetType: String!
      images: [Image!]!
    }
    type ImageWidget implements Widget {
      widgetId: String!
      widgetType: String!
      image: Image
    }
  `;

  createTypes(typeDefs);
}

export const ImageFragment = graphql`
  fragment ImageFragment on Image {
    src {
      childImageSharp {
        fluid {
          ...GatsbyImageSharpFluid
        }
      }
    }
    alt
    caption
  }
`;

export const WidgetFragment = graphql`
  fragment WidgetFragment on Widget {
      widgetId
      widgetType
      ... on ImageListWidget {
        images {
          ...ImageFragment
        }
      }
      ... on ImageWidget {
        image {
          ...ImageFragment
        }
      }
    }
  `
```

Now when it comes time to generate the `<ImageWidget />`, I could type using the generated Fragment types, which are not exported from `graphql-types.ts`:

```ts
type WidgetFragment_ImageSliderWidget_Fragment = (
  Pick<ImageSliderWidget, 'widgetId' | 'widgetType'>
  & { images: Array<Maybe<ImageFragmentFragment>> }
);

type WidgetFragment_ImageWidget_Fragment = (
  Pick<ImageWidget, 'widgetId' | 'widgetType'>
  & { image: Maybe<ImageFragmentFragment> }
);
```

The whole WidgetFragment definition is exported, but there's no way to get the definition I need from it:

```ts
export type WidgetFragmentFragment = WidgetFragment_ImageSliderWidget_Fragment | WidgetFragment_ImageWidget_Fragment;
```

**Comment by d4rekanguok** [comment]
Hey @johnrom, thank you for trying out `gatsby-plugin-graphql-codegen`. I'll look into this as soon as possible.

In the mean time, have you checked out https://github.com/cometkim/gatsby-plugin-typegen ? It does similar thing as this plugin, but it might handle this case. Thanks again!

**Comment by johnrom** [comment]
Interesting, I hadn't come across that plugin. I'll take a look. If it doesn't solve the issue, I'd be willing to open a PR with the fix.

**Comment by johnrom** [comment]
I checked out the other plugin, and that doesn't export the Inline Fragment definitions either. Maybe there's a common library upstream that is generating the types this way?

I'll open an issue there as well.

**Comment by johnrom** [comment]
Found solution, quoting from other issue:

> Looks like the missing config setting is below. I wonder if this can be configured outside of your plugin in a config file? I'm not sure if codegen.yml can be inherited by CLI configuration. Let me know if there's some way to override the configuration or if you're willing to export these types in the default configuration, in which case I can open a PR.

[`@graphql-codegen/typescript-operations`: `config.exportFragmentSpreadSubTypes`](https://graphql-code-generator.com/docs/plugins/typescript-operations#exportfragmentspreadsubtypes-boolean-default-value-false)

**Comment by d4rekanguok** [comment]
Thank you for figuring this one out @johnrom! A PR will highly be appreciated.

I setup typescript-operation config over here: https://github.com/d4rekanguok/gatsby-typescript/blob/74f0f4547c24bbbd035bcf758135e898d04df49a/packages/gatsby-plugin-graphql-codegen/src/graphql-codegen.config.ts#L62

I plan to expose codegen config in a update soon, so users can edit the config as they need.
