### ISSUE TITLE
camel case vs snake case

### ISSUE THREAD

**Issue by Couto** [d4rekanguok/gatsby-typescript#73]
I've used the search in hope for a duplicate.

I'm currently using the https://rickandmortyapi.com/ graphql api.

The types being generated by gatsby-plugin-graphql-codegen are a mixture of camel case and snake case (e.g: `RickAndMorty_Characters`), is there a way of configuring that? Either to only have camel case or snake case?

Thanks

**Comment by d4rekanguok** [comment]
Hi @Couto, thank you for opening an issue! 

I think there's a option you can pass to graphql-codegen to config this, but we have yet to allow custom configurating graphql-codegen —— will work on it sometimes next week, if you'd like you can subscribe to #40. Thanks again!

**Comment by Couto** [comment]
Thanks for the pointer! Will keep an eye on it!

**Comment by d4rekanguok** [comment]
Hey @Couto, we've finally allow passing additional [config & plugins to graphql-codegen!](https://github.com/d4rekanguok/gatsby-typescript/blob/master/packages/gatsby-plugin-graphql-codegen/readme.md#customize-graphql-codegen)

These new options applies to `additionalSchemas` setup as well (which I assume you are using). Here's an example:

```js
exports.default = {
  plugins: [{
    resolve: `gatsby-plugin-graphql-codegen`,
    options: {
      additionalSchemas: [{
        codegenConfig: {
          namingConvention: {
            typeNames: pascal-case#pascalCase,
            transformUnderscore: true
          },
        },
        /* other stuff */
      }],
    }
  }]
}
```

If it still doesn't work & it's possible to share your project, I can take a look. Thanks!

**Comment by Couto** [comment]
Can confirm that it does work indeed! Thank you so much for your time and work! :)
