### ISSUE TITLE
"DEFAULT_SCHEMA_KEY" is not a known API.

### ISSUE THREAD

**Issue by Jdruwe** [d4rekanguok/gatsby-typescript#77]
I get the following error when running gatsby develop:

`- The plugin gatsby-plugin-graphql-codegen@2.6.0 is using the API "DEFAULT_SCHEMA_KEY" which is not a known API.`

Is this an issue on my part?

**Comment by gentksb** [comment]
I faced same problem.

**Comment by ricokahler** [comment]
I can take a look at this tomorrow.

For awareness cc @kije

**Comment by d4rekanguok** [comment]
Ooh we need to move any non-gatsby api exports out of gatsby-node.ts. @Jdruwe @gentksb sorry about this & thank you for reporting in!

**Comment by d4rekanguok** [comment]
We've fixed this in a patch: 
- gatsby-plugin-graphql-codegen@2.6.1

If you're affected by this, please upgrade to the latest version. My apologies for the inconvenience. It's my mistake to not test each plugin individually before publishing.

**Comment by Jdruwe** [comment]
@d4rekanguok please don't apologize, you are doing amazing work with this plugin! Thx for the fix :)
