### ISSUE TITLE
Conflict with `gatsby-plugin-typescript`: const enums are not supported

### ISSUE THREAD

**Issue by ricokahler** [d4rekanguok/gatsby-typescript#95]
It looks like Gatsby has added ["Native support for TypeScript"](https://twitter.com/gatsbyjs/status/1258427651066400768) by always including `gatsby-plugin-typescript` in the build. This most likely conflicts with `gatsby-plugin-ts` thus giving the error message

"const enums are not supported"

This plugin has supported const enums in the past because we run typescript through the typescript compiler before we send it along to the default Gatsby babel compiler (vs the Gatsby-native `gatsby-plugin-typescript` only runs typescript though babel).

---

This is causing a block for my projects at work so I'll have a PR ready soon. It might just be a configuration thing that needs docs but regardless, I'll figure something out!

**Comment by d4rekanguok** [comment]
Shoot, this could be a problem for us. Still, happy with this development in Gatsby!

**Comment by msuntharesan** [comment]
This is being addressed in https://github.com/gatsbyjs/gatsby/pull/26452
