### ISSUE TITLE
Is there a way to generate graphql-type outside gatsby?

### ISSUE THREAD

**Issue by iray-tno** [d4rekanguok/gatsby-typescript#98]
Thanks for the awesome project. :)

**Describe the bug**
I'm using `gatsby-plugin-graphql-codegen` with the official typescript plugin.
And I'm not adding the generated file to git.

In my case, when I clone my project and start development in another env, the build always fails since the type file doesn't exist.

```
yarn run v1.22.4
$ gatsby build
success open and validate gatsby-configs - 0.063s

 ERROR 

Error in "D:\HogeHoge\chirashi_js\gatsby-node.js": ⨯ Unable to compile TypeScript:
src/gatsbyNode/createPages.ts:3:42 - error TS2307: Cannot find module '../../types/graphqlTypes'.

3 import { MarkdownRemarkConnection } from '../../types/graphqlTypes';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Is there a way to generate graphql-type outside gatsby?

Thanks.

**To Reproduce**
- clone my project https://github.com/iray-tno/chirashi-js
- yarn install
- yarn build

**Environment (please complete the relevant info):**
- OS: Windows
- Gatsby version: 2.22.9
- Typescript version: 3.8.3

**Comment by iray-tno** [comment]
Oh, sorry, this looks like dups with #76 .
If so, this issue can be closed.

**Comment by d4rekanguok** [comment]
Thanks for your interest in this project @iray-tno! #76 will indeed solve this issue. I'll close this for now, but will ping you when it is resolved.
